import type {Metadata} from "next"
import {Geist, Geist_Mono} from "next/font/google"

import {AppSidebar} from "./_components/sidebar/app-sidebar"
import {SidebarProvider, SidebarTrigger} from "./_components/sidebar/sidebar"
import {SWRProvider} from "./_providers/swr-provider"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SWRProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger className="fixed top-5 left-2 z-50 lg:hidden" />
            {children}
          </SidebarProvider>
        </SWRProvider>
      </body>
    </html>
  )
}
