name: API Tests

permissions:
  contents: read

on:
  push:
    branches: ["main"]

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # - name: Run API Tests
      #   run: pnpm test:api:bruno:prod
